# Generated by Django 5.2.6 on 2025-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='active_player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='room_name',
            field=models.CharField(default='default_room', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WIN_P1', 'Player 1 won'), ('WIN_P2', 'Player 2 won'), ('TIE', 'Tie')], default='ACTIVE', max_length=10),
        ),
    ]
